const placeholderContent = () => [
  {
    title: 'Tester I',
    product: 'Acrobat',
    posType: 'Temporary',
    department: 'Testing',
    city: 'Seattle',
  },
  {
    title: 'Tester II',
    product: 'Acrobat',
    posType: 'Perminant',
    department: 'Testing',
    city: 'Seattle',
  },
  {
    title: 'Tester III',
    product: 'Acrobat',
    posType: 'Internship',
    department: 'Testing',
    city: 'Seattle',
  },
  {
    title: 'Sr Tester',
    product: 'Acrobat',
    posType: 'Perminant',
    department: 'Testing',
    city: 'San Fransisco',
  },
  {
    title: 'Jr Tester',
    product: 'Acrobat',
    posType: 'Perminant',
    department: 'Testing',
    city: 'San Fransisco',
  },
  {
    title: 'Mid Tester',
    product: 'Acrobat',
    posType: 'Apprenticeship',
    department: 'Testing',
    city: 'San Fransisco',
  },
  {
    title: 'Senior Experience Design Manager',
    product: 'Long Position Name',
    posType: 'Perminant',
    department: 'Experience Design',
    city: 'San Fransisco',
  },
  {
    title: 'UI/UX Lead',
    product: 'Acrobat',
    posType: 'Perminant',
    department: 'Testing',
    city: 'San Fransisco',
  },
  {
    title: 'Scrum Master',
    product: 'Acrobat',
    posType: 'Internship',
    department: 'Testing',
    city: 'San Fransisco',
  },
  {
    title: 'Sr Test Designer',
    product: 'Adobe Poduct',
    posType: 'Perminant',
    department: 'Design',
    city: 'Lehi',
  },
  {
    title: 'Jr Test Specialist',
    product: 'Acrobat',
    posType: 'Perminant',
    department: 'Testing',
    city: 'Lehi',
  },
  {
    title: 'Manager of Testing',
    product: 'Adobe Poduct',
    posType: 'Internship',
    department: 'Testing',
    city: 'New York',
  },
];

export default placeholderContent;
